DB_Realize_OnlineLibrary/Controllers/FinesController.cs
using DB_Realize_OnlineLibrary.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DB_Realize_OnlineLibrary.Controllers
{
    public class FinesController : Controller
    {
        LibraryContext _db;
        IWebHostEnvironment _environment;
        private readonly UserManager<Reader> _userManager;
        public FinesController(LibraryContext db, IWebHostEnvironment hostEnvironment, UserManager<Reader> userManager)
        {
            _db = db;
            _environment = hostEnvironment;
            _userManager = userManager;
        }
        [Authorize]
        public IActionResult Index()
        {
            var userId = _userManager.GetUserId(User);
            var fineList = _db.Fines.Where(x => x.ReaderId == userId).Include(b => b.Book).ToList();
            return View(fineList);
        }

        [Authorize]
        [HttpGet]
        public IActionResult Pay(int? id)
        {
            if (id == null)
                return NotFound();
            var fine = _db.Fines.Include(f => f.Book).FirstOrDefault(f => f.Id == id);
            if (fine == null)
                return NotFound();
            return View(fine);
        }

        [Authorize]
        [HttpPost]
        public IActionResult Pay(Fine fine)
        {
            if (fine != null)
            {
                fine.Status = "Оплачено";
                _db.Entry(fine).State = EntityState.Modified;
                _db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

DB_Realize_OnlineLibrary/Controllers/MyBooksController.cs
using DB_Realize_OnlineLibrary.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DB_Realize_OnlineLibrary.Controllers
{
    public class MyBooksController : Controller
    {
        LibraryContext _db;
        IWebHostEnvironment _environment;
        private readonly UserManager<Reader> _userManager;
        public MyBooksController(LibraryContext db, IWebHostEnvironment hostEnvironment, UserManager<Reader> userManager)
        {
            _db = db;
            _environment = hostEnvironment;
            _userManager = userManager;
        }

        [Authorize]
        public IActionResult Index()
        {
            var userId = _userManager.GetUserId(User);
            var historyList = _db.History.Where(x => x.ReaderId == userId).Include(b => b.Book).ToList();
            return View(historyList);
        }

        [Authorize]
        [HttpGet]
        public IActionResult Return(int? id)
        {
            if (id == null)
                return NotFound();
            var historyItem = _db.History.Include(f => f.Book).FirstOrDefault(f => f.Id == id);
            if (historyItem == null)
                return NotFound();
            return View(historyItem);
        }

        [Authorize]
        [HttpPost]
        public IActionResult Return(HistoryItem historyItem)
        {
            if (historyItem != null)
            {
                historyItem.DateofDelivery = DateTime.Now;
                if (historyItem.DateofDelivery > historyItem.ExpectedDateOfDelivery)
                {
                    int overdue = ((DateTime)historyItem.DateofDelivery).Day - ((DateTime)historyItem.ExpectedDateOfDelivery).Day + 1;
                    var fine = new Fine()
                    {
                        ReaderId = historyItem.ReaderId,
                        BookId = historyItem.BookId,
                        IsMess = false,
                        OverdueDays = overdue,
                        Price = overdue*100,
                        Status = "Не оплачено"
                    };
                    _db.Fines.Add(fine);
                }
                var book = _db.Books.FirstOrDefault(x => x.Id == historyItem.BookId);
                book.Quantity++;
                _db.Entry(book).State = EntityState.Modified;
                _db.Entry(historyItem).State = EntityState.Modified;
                _db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

DB_Realize_OnlineLibrary/Controllers/UserController.cs
using DB_Realize_OnlineLibrary.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Hosting;

namespace DB_Realize_OnlineLibrary.Controllers
{
    public class UserController : Controller
    {
        private readonly SignInManager<Reader> _signInManager;
        private readonly UserManager<Reader> _userManager;
        LibraryContext _db;
        IWebHostEnvironment _environment;

        public UserController(SignInManager<Reader> signInManager, UserManager<Reader> userManager, LibraryContext db, IWebHostEnvironment hostEnvironment)
        {
            _signInManager = signInManager;
            _userManager = userManager;
            _db = db;
            _environment = hostEnvironment;
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterUser model)
        {
            if (ModelState.IsValid)
            {
                var user = new Reader { UserName = model.Username, PasswordHash = model.Password, Name = model.Name, DateofBirth = model.DateofBirth };
                var result = await _userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    await _signInManager.SignInAsync(user, isPersistent: false);
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginUser model)
        {
            if (ModelState.IsValid)
            {
                var result = await _signInManager.PasswordSignInAsync(model.Username, model.Password, isPersistent: false, lockoutOnFailure: false);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index", "Home");
                }
                ModelState.AddModelError(string.Empty, "Invalid login attempt.");
                return View(model);
            }
            return View(model);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Profile()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
                return NotFound();
            if(user.GroupId != null)
                ViewBag.GroupName = _db.GroupReaders.FirstOrDefault(g => g.Id == user.GroupId);
            return View(user);
        }
    }
}

DB_Realize_OnlineLibrary/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DB_Realize_OnlineLibrary</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DB_Realize_OnlineLibrary.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Библиотека</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="MyBooks" asp-action="Index">Мои книги</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Fines" asp-action="Index">Мои штрафы</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Groups" asp-action="Index">Группы</a>
                            </li>
                        }

                    </ul>
                    <ul class="navbar-nav">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Добро пожаловать, @User.Identity.Name!
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item btn btn-link" asp-area="Identity" asp-controller="User" asp-action="Profile">Профиль</a>
                                    <form id="logoutForm" asp-area="Identity" asp-controller="User" asp-action="Logout" method="post" class="d-inline">
                                        <button type="submit" class="dropdown-item btn btn-link">Выйти</button>
                                    </form>
                                </div>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="Identity" asp-controller="User" asp-action="Login">Вход</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="Identity" asp-controller="User" asp-action="Register">Регистрация</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - DB_Realize_OnlineLibrary - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>