DB_Realize_OnlineLibrary/Controllers/FinesController.cs
using DB_Realize_OnlineLibrary.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DB_Realize_OnlineLibrary.Controllers
{
    public class FinesController : Controller
    {
        LibraryContext _db;
        IWebHostEnvironment _environment;
        private readonly UserManager<Reader> _userManager;
        public FinesController(LibraryContext db, IWebHostEnvironment hostEnvironment, UserManager<Reader> userManager)
        {
            _db = db;
            _environment = hostEnvironment;
            _userManager = userManager;
        }
        [Authorize]
        public IActionResult Index()
        {
            var userId = _userManager.GetUserId(User);
            var fineList = _db.Fines.Where(x => x.ReaderId == userId).Include(b => b.Book).ToList();
            return View(fineList);
        }

        [Authorize]
        [HttpGet]
        public IActionResult Pay(int? id)
        {
            if (id == null)
                return NotFound();
            var fine = _db.Fines.Include(f => f.Book).FirstOrDefault(f => f.Id == id);
            if (fine == null)
                return NotFound();
            return View(fine);
        }

        [Authorize]
        [HttpPost]
        public IActionResult Pay(Fine fine)
        {
            if (fine != null)
            {
                fine.Status = "Оплачено";
                _db.Entry(fine).State = EntityState.Modified;
                _db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

DB_Realize_OnlineLibrary/Controllers/ReviewController.cs
using DB_Realize_OnlineLibrary.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DB_Realize_OnlineLibrary.Controllers
{
    public class ReviewController : Controller
    {
        LibraryContext _db;
        UserManager<Reader> _userManager;
        public ReviewController(LibraryContext context, UserManager<Reader> userManager)
        {
            _db = context;
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Reviews(int id)
        {
            var book = _db.Books.Include(g => g.Genre).Include(p => p.Publisher).Include(c => c.Condition).FirstOrDefault(f => f.Id == id);
            var reviews = _db.Reviews.Where(r => r.BookId == id).ToList();
            double TotalRating = 0;
            if (reviews.Count() > 0)
            {
                foreach (var review in reviews)
                    TotalRating += review.Rating;
                TotalRating /= reviews.Count();
            }
            ViewBag.TotalRating = TotalRating;
            ViewBag.Book = book;
            ViewBag.Reviews = reviews;
            if (User.Identity.IsAuthenticated)
            {
                Reader user = await _userManager.GetUserAsync(User);
                ViewBag.CheckRead = checkBookForUser(id).GetAwaiter().GetResult();
            }
            return View();
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Add(Review review)
        {
            if (review == null)
                return NotFound();
            if (review.Rating == 0)
                review.Rating = 5;
            Reader user = await _userManager.GetUserAsync(User);
            review.DatePosted = DateTime.Now;
            review.ReaderId = user.Id;
            review.UserName = user.UserName;
            var existingReview = _db.Reviews.Where(r => r.ReaderId == review.ReaderId).FirstOrDefault(r => r.BookId == review.BookId);
            if (existingReview != null)
            {
                existingReview.DatePosted = review.DatePosted;
                existingReview.Text = review.Text;
                existingReview.Rating = review.Rating;
                _db.Entry(existingReview).State = EntityState.Modified;
            }
            else
                _db.Reviews.Add(review);
            _db.SaveChanges();
            return RedirectToAction("Reviews", new { id = review.BookId });
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int? id)
        {
            Review review = _db.Reviews.Include(r => r.Book).FirstOrDefault(review => review.Id == id);
            return View(review);
        }
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(Review review)
        {
            if (review != null)
            {
                _db.Entry(review).State = EntityState.Deleted;
                _db.SaveChanges();
            }
            return RedirectToAction("Reviews", new { id = review.BookId });
        }


        public async Task<bool> checkBookForUser(int id)
        {
            Reader user = await _userManager.GetUserAsync(User);
            List<HistoryItem> BooksInHistory = _db.History.Where(r => r.ReaderId == user.Id).ToList();
            List<int> readId = new List<int>();
            foreach (var item in BooksInHistory)
            {
                readId.Add(item.BookId);
            }
            return readId.Contains(id);
        }
    }
}

DB_Realize_OnlineLibrary/Controllers/UserController.cs
using DB_Realize_OnlineLibrary.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Hosting;

namespace DB_Realize_OnlineLibrary.Controllers
{
    public class UserController : Controller
    {
        private readonly SignInManager<Reader> _signInManager;
        private readonly UserManager<Reader> _userManager;
        LibraryContext _db;
        IWebHostEnvironment _environment;

        public UserController(SignInManager<Reader> signInManager, UserManager<Reader> userManager, LibraryContext db, IWebHostEnvironment hostEnvironment)
        {
            _signInManager = signInManager;
            _userManager = userManager;
            _db = db;
            _environment = hostEnvironment;
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterUser model)
        {
            if (ModelState.IsValid)
            {
                var user = new Reader { UserName = model.Username, PasswordHash = model.Password, Name = model.Name, DateofBirth = model.DateofBirth };
                var result = await _userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    await _signInManager.SignInAsync(user, isPersistent: false);
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginUser model)
        {
            if (ModelState.IsValid)
            {
                var result = await _signInManager.PasswordSignInAsync(model.Username, model.Password, isPersistent: false, lockoutOnFailure: false);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index", "Home");
                }
                ModelState.AddModelError(string.Empty, "Invalid login attempt.");
                return View(model);
            }
            return View(model);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Profile()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
                return NotFound();
            if(user.GroupId != null)
                ViewBag.GroupName = _db.GroupReaders.FirstOrDefault(g => g.Id == user.GroupId);
            return View(user);
        }
    }
}

DB_Realize_OnlineLibrary/Views/Home/Create.cshtml
@model DB_Realize_OnlineLibrary.Models.Book

@{
    ViewData["Title"] = "Create";
}

<h1>Добавить книгу</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Author" class="control-label"></label>
                <input asp-for="Author" class="form-control" />
                <span asp-validation-for="Author" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Days" class="control-label"></label>
                <input asp-for="Days" class="form-control" />
                <span asp-validation-for="Days" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year" class="control-label"></label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <select asp-for="GenreId" class ="form-control" asp-items="ViewBag.Genre"></select>
            </div>
            <div class="form-group">
                <label asp-for="Publisher" class="control-label"></label>
                <select asp-for="PublisherId" class ="form-control" asp-items="ViewBag.Publisher"></select>
            </div>
            <div class="form-group">
                <label asp-for="Condition" class="control-label"></label>
                <select asp-for="ConditionId" class="form-control" asp-items="ViewBag.Condition"></select>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Выберите файл для загрузки</label>
                <input type="file" name="upload" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Добавить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Назад к списку</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DB_Realize_OnlineLibrary/Views/Home/Edit.cshtml
@model DB_Realize_OnlineLibrary.Models.Book

@{
    ViewData["Title"] = "Edit";
}

<h1>Редактирование</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Author" class="control-label"></label>
                <input asp-for="Author" class="form-control" />
                <span asp-validation-for="Author" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Days" class="control-label"></label>
                <input asp-for="Days" class="form-control" />
                <span asp-validation-for="Days" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year" class="control-label"></label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <select asp-for="GenreId" class="form-control" asp-items="ViewBag.Genre"></select>
                <span asp-validation-for="GenreId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Publisher" class="control-label"></label>
                <select asp-for="PublisherId" class="form-control" asp-items="ViewBag.Publisher"></select>
                <span asp-validation-for="Condition" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Condition" class="control-label"></label>
                <select asp-for="ConditionId" class="form-control" asp-items="ViewBag.Condition"></select>
                <span asp-validation-for="Condition" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Выберите файл для загрузки</label>
                <input type="file" name="upload" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Назад к списку</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DB_Realize_OnlineLibrary/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Identity
@{
    var titleFilter = ViewBag.TitleFilter as string ?? "";
    var authorFilter = ViewBag.AuthorFilter as string ?? "";
    var publisherFilter = ViewBag.PublisherFilter as string ?? "";
}
<style>
    .book-container {
        display: flex;
        flex-wrap: wrap;
        justify-content: space-between;
        margin-bottom: 20px;
    }

    .book-item {
        width: calc(50% - 10px);
        min-width: 300px; /* Минимальная ширина элемента */
        margin-bottom: 20px;
        line-height: 1.4;
        border: 1px solid #ccc;
        padding: 20px;
        box-sizing: border-box;
    }

    .book-name {
        font-size: 24px;
        font-weight: bold;
        margin-bottom: 10px;
    }

    .book-details {
        flex-grow: 1;
    }

    .book-info p {
        margin-bottom: 10px;
    }

    .btn-group {
        align-self: flex-end;
    }

    .img-container {
        width: 100%;
        max-width: 368px;
        height: auto;
        border: 1px solid #ccc;
    }

    .btn {
        margin: 10px 0px 10px 0px;
    }
</style>


<h1>Фильмы</h1>

@if (User.IsInRole("Admin"))
{
    <div style="display:inline-flex">
        <p>
            <a class="btn btn-primary" asp-action="Create">Добавить новую книгу</a>
        </p>
        <p>
            <a class="btn btn-primary" asp-action="Create" asp-controller="Publisher">Добавить новое издательство</a>
        </p>
        <p>
            <a class="btn btn-primary" asp-action="Create" asp-controller="Genre">Добавить новый жанр</a>
        </p>
        <p>
            <a class="btn btn-primary" asp-action="Create" asp-controller="Condition">Добавить новое состояние</a>
        </p>
    </div>
}

<button class="btn btn-secondary" onclick="toggleFilter()">Показать/Скрыть фильтр</button>

<div id="filterForm" style="display: none; margin-top: 20px;">
    <form method="get" asp-action="Index">
        <div class="form-group">
            <label for="title">Название</label>
            <input type="text" name="title" id="title" class="form-control" value="@titleFilter" />
        </div>
        <div class="form-group">
            <label for="author">Автор</label>
            <input type="text" name="author" id="author" class="form-control" value="@authorFilter" />
        </div>
        <div class="form-group">
            <label for="publisher">Издательство</label>
            <input type="text" name="publisher" id="publisher" class="form-control" value="@publisherFilter" />
        </div>
        <button type="submit" class="btn btn-primary">Поиск</button>
    </form>
</div>

<div class="book-container">
    @foreach (var item in Model)
    {
        <div class="book-item">
            <div class="img-container">
                @if (!string.IsNullOrEmpty(item.ImageUrl))
                {
                    <img src="@Url.Content("~/images/")@item.ImageUrl" alt="@item.Name" class="card-img-top" />
                }
                else
                {
                    <img src="@Url.Content("~/images/")null_image.jpg" alt="@item.Name" class="card-img-top" />
                }
            </div>
            <div class="book-details">
                <p class="book-name">@item.Name</p>
                <div class="book-info">
                    <p><strong>Автор:</strong> @item.Author</p>
                    <p><strong>Издательство:</strong> @item.Publisher.Name</p>
                    <p><strong>Год:</strong> @item.Year</p>
                    <p><strong>Жанр:</strong> @item.Genre.Name</p>
                    <p><strong>Срок возврата:</strong> @item.Days дней</p>
                    <p><strong>Кол-во в библиотеке:</strong> @item.Quantity</p>
                    <p><strong>Цена:</strong> @item.Price</p>
                </div>
                @if (User.IsInRole("Admin"))
                {
                    bool inCart = false;
                    <div class="btn-group">
                        <a class="btn btn-info" asp-action="Reviews" asp-controller="Review" asp-route-id="@item.Id">Отзывы</a>
                        <a class="btn btn-info" asp-action="Edit" asp-route-id="@item.Id">Изменить</a>
                        <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Id">Удалить</a>
                    </div>
                }
                else if (User.Identity.IsAuthenticated)
                {
                    bool inRent = ViewBag.Rent.Contains(item.Id);
                    <div class="card-footer">
                        @if (ViewBag.IsFine)
                        {
                            <a asp-action="Index" asp-controller="Fines" class="btn btn-info" style="background-color: red; border:none">Оплатите штрафы</a>
                        }
                        else if (inRent)
                        {
                            <a href="#" class="btn btn-info" style="background-color: green; border:none">&#10003; Уже у вас</a>
                        }
                        else if (item.Quantity == 0)
                        {
                            <a href="#" class="btn btn-info" style="background-color: deeppink; border:none">Закончился</a>
                        }
                        else
                        {
                            <form asp-action="Rent" asp-route-id="@item.Id" method="post">
                                <button class="btn btn-info">Арендовать</button>
                            </form>
                        }
                        <a class="btn btn-info" asp-action="Reviews" asp-controller="Review" asp-route-id="@item.Id">Отзывы</a>
                    </div>
                }
                else
                {
                    <div class="card-footer">
                        @if (item.Quantity == 0)
                        {
                            <a href="#" class="btn btn-info" style="background-color: deeppink; border:none">Закончился</a>
                        }
                        else
                        {
                            <a asp-area="Identity" asp-controller="User" asp-action="Login" class="btn btn-info">Арендовать</a>
                        }
                        <a class="btn btn-info" asp-action="Reviews" asp-controller="Review" asp-route-id="@item.Id">Отзывы</a>
                    </div>
                }
            </div>
        </div>
    }
</div>

@section Scripts {
    <script>
        function toggleFilter() {
            var filterForm = document.getElementById("filterForm");
            if (filterForm.style.display === "none" || filterForm.style.display === "") {
                filterForm.style.display = "block";
            } else {
                filterForm.style.display = "none";
            }
        }
    </script>
}